[package]
name = "faiyels"
version = "0.1.0"
authors = ["Tristan Hume <tristan@thume.ca>"]

[dependencies]
conrod = "0.35.0"
find_folder = "0.3.0"
vecmath = "0.2.0"
piston_window = "0.47.0"
gfx = "0.11.0"
cgmath = "0.9.1"
walkdir = "0.1.5"
syntect = "0.7.0"
